dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules

before_install:
  - npm install -g yarn --cache-min 999999999

install:
  - yarn

script:
  - yarn build
